### ISSUE TITLE
version issue

### ISSUE THREAD

**Issue by sjspielman** [clauswilke/dviz.supp#1]
Hi Claus, 

Your `DESCRIPTION` file reads says you're compatible w/ R>=3.3.0, but installation from CRAN says `package ‘dviz.supp’ is not available (for R version 3.4.1)`. It is generally my understanding that 4>3, so this error isn't clear. The current R version is also 3.4.3, so I'm even a little behind. 

Thoughts here?

-Stephanie

**Comment by clauswilke** [comment]
The package is not on CRAN. It will also likely never be on CRAN, because it violates several CRAN policies. [Most importantly, currently: (i) depends on other things not on CRAN; (ii) contains huge amounts of data.] You have to install from github.

**Comment by sjspielman** [comment]
Agreed, in theory. However:
```r
> library(devtools)
Warning message:
package ‘devtools’ was built under R version 3.4.2 

> devtools::install_github("clauswilke/dviz.supp")
Downloading GitHub repo clauswilke/dviz.supp@master
from URL https://api.github.com/repos/clauswilke/dviz.supp/zipball/master
Installing dviz.supp
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/cowplot_0.9.2.tgz'
Content type 'application/x-gzip' length 2442339 bytes (2.3 MB)
==================================================
downloaded 2.3 MB

Installing cowplot
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/tmp/RtmpZCLLGK/devtools256531bd64ea/cowplot'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *binary* package ‘cowplot’ ...
* DONE (cowplot)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/tmp/RtmpZCLLGK/devtools256544efe63f/clauswilke-dviz.supp-afb8fef'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

ERROR: dependency ‘colorblindr’ is not available for package ‘dviz.supp’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/dviz.supp’
Installation failed: Command failed (1)
Warning message:
In strptime(x, fmt, tz = "GMT") :
  unknown timezone 'zone/tz/2017c.1.0/zoneinfo/America/New_York'

> library(dviz.supp)
Error in library(dviz.supp) : there is no package called ‘dviz.supp’
```

**Comment by clauswilke** [comment]
Exactly. As I wrote: "... currently: (i) depends on other things not on CRAN".

https://github.com/clauswilke/colorblindr/blob/master/README.md

**Comment by sjspielman** [comment]
Aha, I understand now. Thanks for your patience.

—
Stephanie J. Spielman
Research Assistant Professor
Institute for Genomics and Evolutionary Medicine
SERC 643
Temple University
http://sjspielman.org

On February 1, 2018 at 12:35:10 PM, Claus Wilke (notifications@github.com) wrote:

Exactly. As I wrote: "... currently: (i) depends on other things not on CRAN".

https://github.com/clauswilke/colorblindr/blob/master/README.md

**Comment by billyarberry** [comment]
I"ve been trying for hours but cannot get dviz.supp to install properly.  Is there a straightforward installation (code) available?  Wilke's book "Fundamentals of Data Visualization" depends on that package.  Thanks

**Comment by clauswilke** [comment]
@billyarberry There seems to be a misunderstanding. The book "Fundamentals of Data Visualization" does certainly not depend on this package. This package is a personal package that I wrote to generate the figures in the book, but the book itself is not a programming book and does not make any reference to any code that would require this package.

I quote from [the preface](https://serialmentor.com/dataviz/preface.html) (emphasis added here): 

> Even though nearly all of the figures in this book were made with R and ggplot2, I do not see this as an R book. I am talking about general principles of figure preparation. The software used to make the figures is incidental. You can use any plotting software you want to generate the kinds of figures I’m showing here. However, ggplot2 and similar packages make many of the techniques I’m using much simpler than other plotting libraries. **Importantly, because this is not an R book, I do not discuss code or programming techniques anywhere in this book.** I want you to focus on the concepts and the figures, not on the code. If you are curious how any of the figures were made, you can check out the book’s source code at its GitHub repository, https://github.com/clauswilke/dataviz. 

If you want to learn how to make figures with R, I recommend [the book by Kieran Healy.](http://socviz.co/) I also have started putting together annotated examples of how I made some of the figures in Fundamentals, and you may find this helpful: https://wilkelab.org/practicalgg/

**Comment by billyarberry** [comment]
Thanks for responding. I had merelyassumed that running downloaded code would be straightforward.  Will check out your reference.  

Sent from Yahoo Mail on Android 
 
  On Thu, Oct 3, 2019 at 10:53 AM, Claus Wilke<notifications@github.com> wrote:   
@billyarberry There seems to be a misunderstanding. The book "Fundamentals of Data Visualization" does certainly not depend on this package. This package is a personal package that I wrote to generate the figures in the book, but the book itself is not a programming book and does not make any reference to any code that would require this package.

I quote from the preface (emphasis added here):


Even though nearly all of the figures in this book were made with R and ggplot2, I do not see this as an R book. I am talking about general principles of figure preparation. The software used to make the figures is incidental. You can use any plotting software you want to generate the kinds of figures I’m showing here. However, ggplot2 and similar packages make many of the techniques I’m using much simpler than other plotting libraries. Importantly, because this is not an R book, I do not discuss code or programming techniques anywhere in this book. I want you to focus on the concepts and the figures, not on the code. If you are curious how any of the figures were made, you can check out the book’s source code at its GitHub repository, https://github.com/clauswilke/dataviz.


If you want to learn how to make figures with R, I recommend the book by Kieran Healy. I also have started putting together annotated examples of how I made some of the figures in Fundamentals, and you may find this helpful: https://wilkelab.org/practicalgg/
